### ISSUE TITLE
Possible glibc issue when installing WiggleTools

### ISSUE THREAD

**Issue by lcolladotor** [Ensembl/WiggleTools#1]
Hello,

I tried installing WiggleTools and encountered a couple errors.

First, there seem to be some minor errors when installing kent. I don't think that the error matters much in this case as it's related to preserving the permissions for some files as shown below.

``` bash
cp -pf gitFiles /home/bst/student/lcollado/software/userApps/scripts/gitFiles
cp: preserving permissions for `/home/bst/student/lcollado/software/userApps/scripts/gitFiles': Operation not supported
cp: preserving ACL for `/home/bst/student/lcollado/software/userApps/scripts/gitFiles': Operation not supported
```

I later encountered a warning when installing WiggleTools which lead to errors. The key part seems to be:

```
in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

These seems different to the errors you anticipated about -lssl or -lcrypto. Right? If so, google lead me to http://stackoverflow.com/questions/2725255/create-statically-linked-binary-that-uses-getaddrinfo which doesn't seem to help in this case. Then from http://bytes.com/topic/c/answers/877929-lnk-error-using-dlopen-statically-linked-apps-requires-runtime-shared-lib I checked the environment variable they mention:

``` bash
22:04 WiggleTools $ echo $LD_LIBRARY_PATH
/hpscc/usr/local/gcc-4.1.2/install/libraries/lib:/opt/gridengine/lib/lx26-amd64:/opt/gridengine/lib/lx26-amd64::/usr/local/atlas/3.9.4/lib:/usr/local/gsl/1.12/lib
```

Could this be a compiler issue? Do you have any suggestions? I could also double check with the system administrators of our cluster environment.

Thank you!
Leonardo
### Log

Here's the full log information https://gist.github.com/lcolladotor/9753882

**Comment by manojsdoshi** [comment]
so how did u manage to do that 
install openssl with krb5 support

**Comment by lcolladotor** [comment]
I never installed `wiggletools`. Our cluster admin did so in the end. Maybe he can tell you how he did it https://jhpce.jhu.edu/contact/

**Comment by dzerbino** [comment]
Thanks to a change of library dependency, neither the Kent nor the SSL libraries need to be installed, so hopefully most of the problems encountered by Leonardo are no longer a concern.
