### ISSUE TITLE
Scaling and computing mean of > 1000 files

### ISSUE THREAD

**Issue by lcolladotor** [Ensembl/WiggleTools#10]
Hi,

I'm scaling some bigwig files and then computing their mean for several sets of bigwig files. This works well on small sets that have, lets say 20 files. But it fails when using a set of 1700 files. The command looks like this:

```
wiggletools write mean.wig mean scale 1 file1.bw scale 2 file2.bw scale 3 file3.bw scale 4.file4.bw
```

On the large set I get the following error:

```
Could not create new thread 11
```

after which the job core dumps.

From looking at the help, I don't see how to control the number of threads.

```
$ wiggletools --help
WiggleTools

Copyright EMBL-EBI, 2013.
Development contact: Daniel Zerbino zerbino@ebi.ac.uk

This library parses wiggle files and executes various operations on them streaming through lazy evaluators.

Inputs:
	The program takes in Wig, BigWig, BedGraph, Bed, BigBed and Bam files, which are distinguished thanks to their suffix (.wig, .bw, .bg, .bed, .bb, .bam respectively).
	Note that wiggletools assumes that every bam file has an index .bai file next to it.

Outputs:
	The program outputs a wiggle file in stdout unless the output is squashed

Command line:
	wiggletools --help
	wiggletools program

Program grammar:
	program = (iterator) | do (iterator) | (statistic) | (extraction)
	statistic = AUC (output) (iterator) | meanI (output) (iterator) | varI (output) (iterator) | pearson (output) (iterator) (iterator) | isZero (iterator)
	output = filename | -
	extraction = profile (output) (int) (iterator) (iterator) | profiles (output) (int) (iterator) (iterator) | histogram (output) (width) (iterator_list)
		| apply_paste (out_filename) (statistic) (bed_file) (iterator)
	iterator = (filename) | (unary_operator) (iterator) | (binary_operator) (iterator) (iterator) | (reducer) (multiplex) | (setComparison) (multiplex) (multiplex)
	unary_operator = unit | write (output) | write_bg (ouput) | smooth (int) | exp | ln | log (float) | pow (float) | offset (float) | scale (float) | gt (float)
	binary_operator = diff | ratio | overlaps | apply (statistic)
	reducer = cat | sum | product | mean | var | stddev | entropy | CV | median | min | max
	iterator_list = (iterator) : | (iterator) (iterator_list)
	multiplex = (iterator_list) | map (unary_operator) (multiplex)
	setComparison = ttest | wilcoxon
	filename = *.wig | *.bw | *.bed | *.bb | *.bg | *.bam
```

Now, the above error happened when requesting a single core on a cluster managed by SGE. If I run it when requesting 15 cores (as shown below), it also leads to the same error.

```
qrsh -pe local 15 -l mem_free=5G,h_vmem=10G
```

Anyhow, I don't know if this is a bug on Wiggletools. I didn't see a way to get the version installed in our cluster, in case that's information you need. 

If there is a limit on the number of files I can process at a time, I could always compute sums of subsets, then the overall sum before scaling by `1/n` where `n =` number of samples.

Thanks,
Leo

**Comment by dzerbino** [comment]
It could well be that you are limited by the system in your number of threads (11 is suspiciously equal to 10 + 1). Could you please check your ulimits and any constraints imposed by SGE?

**Comment by lcolladotor** [comment]
Thanks, let me ask about possible constraints. The ulimit doesn't seem to be the problem though:

```
$ qrsh
$ ulimit
20971520
```

**Comment by muffato** [comment]
Hi Leo, can you try `ulimit -a` as well ? The default ulimit output is for the file-size

**Comment by jhpce** [comment]
On the JHPCE cluster, max-threads on the nodes is set quite high.
```
$ cat /proc/sys/kernel/threads-max 
8271747
```
and "max user processes" should be 1024:

```
[compute-057 /home/mmi/mmill116]$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) 10485760
pending signals                 (-i) 4135873
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1024
virtual memory          (kbytes, -v) 6291456
file locks                      (-x) unlimited

```

**Comment by lcolladotor** [comment]
Hi,

@nellore has run into the same issue before using the JHPCE cluster and got around it by working on subsets of files. That's basically what I did in https://github.com/nellore/runs/blob/3d73253aee7be6ca6ba00c2d9f25703c384c989d/recount2/mean/calculate_means.R#L81-L108

It seems to be working well. At least it did so when I tested it with 100 files and compared the result from using `mean` directly versus summing in pieces then scaling.

I'd close the issue since we have a functioning workaround. But I'm not sure if you want to keep it open as it _might_ be a `wiggletools` issue. Also, it'd be nice to control the number of spawned jobs to play nicely with our SGE system (well, that's a separate issue).

Best,
Leo

**Comment by dzerbino** [comment]
Hello Leo,

I would still like to understand what is happening.

You say that it worked with 100 files, but not 1700 files? 

That's interesting, because each file has a separate thread, so that means it was quite happy to create 100 threads, but in the second instance crashes at thread 11. 

Also, what code have you wrapped around wiggletools? A quick Google around suggests the error message was generated by another language. C is generally not that chatty when it runs out of resources.

Regards,

Daniel

**Comment by lcolladotor** [comment]
Hi Daniel,

Yes, it worked for 100 files but not 1700. It's interesting that the number of threads is related to the number of files because like you said it doesn't match the error message.

The R code I'm using simply generates files with the commands. For example, file `.createWig_SRP069016.sh` whose contents are:

```
wiggletools write /dcl01/leek/data/gtex_work/runs/recount2/mean/means_sra/mean_SRP069016.wig mean scale 0.0827239031607713 /dcl01/leek/data/sra/v2/batch_72/coverage_bigwigs/SRR3132974.bw scale 0.13169392577408 /dcl01/leek/data/sra/v2/batch_21/coverage_bigwigs/SRR3132975.bw
```

It then uses the following R call to run the job: 

```
system('sh .createWig_SRP069016.sh')
```

That's with the code I wrote. @nellore used another language (was it python?) to wrap around wiggletools.

I don't know if there is a limit in the number of characters in a command that wiggletools can handle (or `sh`). I did try writing the commands with one _iterator_ (like `scale`) per line, but that didn't work either.

Best,
Leo

**Comment by dzerbino** [comment]
There is indeed a possible limitation on the command line, especially within wrapper languages such as R. I know it hits in Python...

**Comment by lcolladotor** [comment]
Yes, I think that there is a limit in R too. However, I dumped the commands to a file (like `.createWig_SRP069016.sh` above) then simply ran it. That way R should not be the issue. Actually, I could just log into the cluster and simply run the shell file directly (without using R) and would still run into the same error.

**Comment by dzerbino** [comment]
I'd be curious to see what this second trial yields, please keep me informed.

**Comment by lcolladotor** [comment]
Are you referring to running projects greater than 100 files in batches? That just finished (well 1 out of 2039 jobs is still running). In particular the one with over 1700 files finished successfully:

```
logs $ more *.724
::::::::::::::
sra.mean.e1309114.724
::::::::::::::
2016-04-26 02:57:57 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part1.wig
2016-04-26 03:04:12 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part2.wig
2016-04-26 03:11:17 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part3.wig
2016-04-26 03:17:54 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part4.wig
2016-04-26 03:24:32 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part5.wig
2016-04-26 03:31:16 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part6.wig
2016-04-26 03:37:39 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part7.wig
2016-04-26 03:45:32 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part8.wig
2016-04-26 03:53:16 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part9.wig
2016-04-26 04:02:04 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part10.wig
2016-04-26 04:10:56 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part11.wig
2016-04-26 04:19:46 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part12.wig
2016-04-26 04:28:53 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part13.wig
2016-04-26 04:35:07 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part14.wig
2016-04-26 04:42:37 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part15.wig
2016-04-26 04:50:19 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part16.wig
2016-04-26 04:56:18 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part17.wig
2016-04-26 05:02:46 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part18.wig
2016-04-26 05:09:39 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part19.wig
2016-04-26 05:16:38 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part20.wig
2016-04-26 05:25:59 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part21.wig
2016-04-26 05:34:40 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part22.wig
2016-04-26 05:43:53 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part23.wig
2016-04-26 05:52:53 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part24.wig
2016-04-26 06:02:57 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part25.wig
2016-04-26 06:12:23 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part26.wig
2016-04-26 06:22:14 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part27.wig
2016-04-26 06:30:56 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part28.wig
2016-04-26 06:40:10 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part29.wig
2016-04-26 06:49:12 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part30.wig
2016-04-26 06:58:03 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part31.wig
2016-04-26 07:06:48 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part32.wig
2016-04-26 07:15:39 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part33.wig
2016-04-26 07:23:52 creating file /scratch/temp/1309114.724.shared.q/Rtmp6zB7SL/sum_SRP025982_part34.wig
2016-04-26 09:29:43 creating file /dcl01/leek/data/gtex_work/runs/recount2/mean/means_sra/mean_SRP025982.bw
2016-04-26 10:27:29
Session info -----------------------------------------------------------------------------------------------------------
Packages ---------------------------------------------------------------------------------------------------------------
::::::::::::::
sra.mean.o1309114.724
::::::::::::::
**** Job starts project SRP025982 ****
Tue Apr 26 02:57:52 EDT 2016
    user   system  elapsed
7747.045  137.497 7243.412
    user   system  elapsed
2454.154  949.265 3465.480
     user    system   elapsed
35617.561  1939.143 26976.000
 setting  value
 version  R version 3.3.0 beta (2016-04-25 r70547)
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       <NA>
 date     2016-04-26

 package      * version  date       source
 acepack        1.3-3.3  2014-11-24 CRAN (R 3.3.0)
 cluster        2.0.4    2016-04-18 CRAN (R 3.3.0)
 colorspace     1.2-6    2015-03-11 CRAN (R 3.3.0)
 devtools       1.10.0   2016-01-23 CRAN (R 3.3.0)
 digest         0.6.9    2016-01-08 CRAN (R 3.3.0)
 foreign        0.8-66   2015-08-19 CRAN (R 3.3.0)
 Formula        1.2-1    2015-04-07 CRAN (R 3.3.0)
 getopt       * 1.20.0   2013-08-30 CRAN (R 3.3.0)
 ggplot2        2.1.0    2016-03-01 CRAN (R 3.3.0)
 gridExtra      2.2.1    2016-02-29 CRAN (R 3.3.0)
 gtable         0.2.0    2016-02-26 CRAN (R 3.3.0)
 Hmisc          3.17-3   2016-04-03 CRAN (R 3.3.0)
 lattice        0.20-33  2015-07-14 CRAN (R 3.3.0)
 latticeExtra   0.6-28   2016-02-09 CRAN (R 3.3.0)
 Matrix         1.2-5    2016-04-17 CRAN (R 3.3.0)
 memoise        1.0.0    2016-01-29 CRAN (R 3.3.0)
 munsell        0.4.3    2016-02-13 CRAN (R 3.3.0)
 nnet           7.3-12   2016-02-02 CRAN (R 3.3.0)
 plyr           1.8.3    2015-06-12 CRAN (R 3.3.0)
 RColorBrewer   1.1-2    2014-12-07 CRAN (R 3.3.0)
 Rcpp           0.12.4.5 2016-04-18 local
 rpart          4.1-10   2015-06-29 CRAN (R 3.3.0)
 scales         0.4.0    2016-02-26 CRAN (R 3.3.0)
 survival       2.39-2   2016-04-16 CRAN (R 3.3.0)
**** Job ends ****
Tue Apr 26 10:27:53 EDT 2016
```

It just takes a bit of time, that's all: 26976 / 60^2 = 7.49 hrs

**Comment by dzerbino** [comment]
Cool, thanks!

**Comment by jgaupp-accuragen** [comment]
I'd like to follow up on this old issue if anyone currently supporting wiggletools is familiar.

I'm also debugging a `Could not create new thread 11` error.  I'll note that 11 isn't a thread limit but the EAGAIN error value returned from failed thread creation.  I suspect my problem happens closer to 100,000 threads.

I'm running a workflow derived from that published by the wiggletools authors that chains wiggletools into wigToBigWig and bigWigCat.

I'm summing position-wise data from a whole genome sequencing run of 2.5 billion reads, 250 bases per read, split into 4,000 bigBed input files.  When successful, the entire process uses around 720GB of RAM, across 128 wiggletools processes, summing the position data in the 4,000 input files into a single ~13GB bigBed file in around 15 minutes.

This works fine on a properly sized server hosting the data locally but runs into thread creation limits when relying on an equivalent server with a cloud based file system intermediary.  Specifically, I'm talking about AWS and Fusion.  The limit may be a hard coded threading limit but could easily be an implicit limit caused by memory exhaustion.

I don't consider the failure wiggletools specific, it's clearly a matter of computing environment and the volume of data.  What I am curious about is how many threads wiggletools might spawn and if there's a way to regulate threads created by the main process?  When running Top with thread counting, I see the 128 wiggletools instances each owning 35 threads, on average, and spiking to around 1,000 for short bursts.  At this point, I'm trusting Top but I'm still early in the investigation.  I'll also dig into the wiggletools code to see if I can reach an independent understanding.

If the threading numbers make sense and are an aspect of the application that isn't tunable, do you have any comments on the setup or an alternate approach for processing data at this volume at speed?  To be fair, I assume the answer is either reorganizing and staggering the processing of the inputs and accepting the performance hit that come along with the specific limitation of my compute environment.

**Comment by dzerbino** [comment]
Hello @jgaupp-accuragen ,

A thread is created for each compressed file (BAM, BCF, BigBed, BigWig) that is being read to allow for decompression to  work at its own pace, especially when the file is remote and there is IO latency between blocks. A final thread is created for writing files. In short, it would be a lot of work to switch off or curb.

Hope this helps, 

Daniel

**Comment by dzerbino** [comment]
PS In terms of advice reducing the latency or reducing the number of processes appear to be the best way forward.

**Comment by jgaupp-accuragen** [comment]
@dzerbino 

I appreciate the timely feedback.  What you described is what I expected after thinking through the situation.  And it's very helpful to have those expectations confirmed, along with the practical suggestions.  

I suspect I (or we) will try to tune the virtual file system and if that's not an option switch back to the local file system for this operation to maintain the all-out runtime efficiency wiggletools provides.  Otherwise, as you suggest, a performance trade-off to avoid overrunning resources.

Thanks for the support.
