### ISSUE TITLE
easy_install.sh chokes of gsl install on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by quantumdot** [Ensembl/WiggleTools#12]
Trying to install WiggleTools using `easy_install.sh` on Ubuntu 14.04 LTS results in an error when attempting to install prerequisite GSL. It appears the the apt package manager has different naming convention for the package `libgsl0` -> `libgsl0ldbl`. Also see [this thread for gsl package names](http://askubuntu.com/questions/490465/install-gnu-scientific-library-gsl-on-ubuntu-14-04-via-terminal)

Manually installing libgsl0ldbl via `apt-get install libgsl0ldbl` followed by running `easy_install.sh` results in successful compilation.

**Comment by dzerbino** [comment]
Thanks for the tip!
