### ISSUE TITLE
build script without sudo?

### ISSUE THREAD

**Issue by sitag** [Ensembl/WiggleTools#14]
Is is possible to gave a build script that doesn't use sudo? Libraries can all be installed locally with LD_LIBRARY_PATH, LIBRARY_PATH, and header paths adjusted. If you don't have root building these manually is a big investment just to try something out.

**Comment by dzerbino** [comment]
Could do, it's just that it opens up a whole other bag of problems. You can try the executables, though.

**Comment by dzerbino** [comment]
The dependency on the Kent library having been removed, I think it would be realistic to review the build script. I'll get round to it when I have a moment.

**Comment by dzerbino** [comment]
You can now install WiggleTools and all its dependencies via the brew package manager for MacOS and Linux. Hopefully this will sort out all installation issues.
