### ISSUE TITLE
mwrite_bg cannot write zero?

### ISSUE THREAD

**Issue by karl616** [Ensembl/WiggleTools#15]
Thanks for a nice tool!

I'm currently trying to merge multiple bigWig files into a single big table and thought mwrite_bg would be a good tools to use. In this case, the bigWig files sometimes cover different regions and it seems as if mwrite_bg introduces ones instead of zeros for uncovered regions. 

wiggletools_x86_64_linux mwrite_bg - *.bw |grep -n -w "0.000000"

The above command identifies zeros on the first three columns, and nothing beyond that.

Is there something obvious I'm missing?

Best,
Karl

**Comment by dzerbino** [comment]
This bug does reproduce with the last release binary, but magically disappeared in the latest version! 

I updated the release binary, please re-download it and try again.
