### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by sklasfeld** [Ensembl/WiggleTools#16]
When I run the wiggletools mean function on two files of size 92M and 127M, I get the following error: 
`Segmentation fault: 11`
Wiggletools works for smaller files, but otherwise doesn't print out anything.

**Comment by dzerbino** [comment]
Hello @sklasfeld , apologies for the slow response. 

Could you please send me the exact command line used?

Thank you,

Daniel

**Comment by sklasfeld** [comment]
I think the file was somehow corrupt. Thanks for getting back to me!

**Comment by sklasfeld** [comment]
The code was `wiggletools write output.wig diff rep1.bw rep2.bw` but as I tried other tools to process the code I found out something was weird with one of the files.

**Comment by dzerbino** [comment]
Ah, in that case, I'll ignore for the moment, but do let me know if it recurs.

Thank you for the bug report,

Daniel
