### ISSUE TITLE
output of CV iterator

### ISSUE THREAD

**Issue by ChiWPak** [Ensembl/WiggleTools#20]
Obtaining unexpected output using the CV function

chr1    0       249239823       nan
chr10   0       135499788       nan
chr11   0       134946510       nan
chr12   0       133833357       nan
chr13   0       115084925       nan
etc...

Using the same set of input files, but with the sum function, I obtain expected results
chr1    0       10444   0.000000
chr1    10444   10609   0.043840
chr1    10609   13296   0.000000
chr1    13296   13461   0.043840
chr1    13461   17353   0.000000
chr1    17353   17517   0.043400
etc...

Do I need to fill in default values? Or is this a bug?

**Comment by dzerbino** [comment]
Hello @ChiWPak, 

Apologies for the slow reply. 

How could I reproduce this bug?

Daniel

**Comment by ChiWPak** [comment]
Hi Daniel,

Sorry but I'm experiencing issues with my computer which won't be fixed for
3-5 days. Waiting for a part. Once it's fixed I'll try to forward you a
small reproducible example. (I'm on mobile)

Chi

**Comment by ChiWPak** [comment]
Sorry again for the delay...

Here are the commands I'm running

    wiggletools write out_sum.txt sum fi1.bw fi2.bw

    wiggletools write out_CV.txt CV fi1.bw fi2.bw

The bigwig files I'm using are >1 GB, but if you cannot reproduce the issue
with some BW files of your own, I'll attempt to make smaller BW files to
share with you that recreate the issue.

Thanks, Chi

**Comment by dzerbino** [comment]
OK, I can reproduce it, I'll have a look sometime next week.

**Comment by dzerbino** [comment]
What do you know, a meeting was cancelled and the bug was embarrassingly trivial, fixed on master.

**Comment by ChiWPak** [comment]
That's good news! Thanks!
