### ISSUE TITLE
bedGraph error line & Segmentation fault 

### ISSUE THREAD

**Issue by LucoLab** [Ensembl/WiggleTools#22]
I have two replicates and one input. They are all in bam format.
I'm trying to create a mean wig and then remove the signal from input bam and keep only positive difference values. So i'm doing what follows but i get the error mentionned in the title of the issue, any idea ?

```
wiggletools write mean.wig Rep1.bam Rep2.bam
wiggletools write mean.normalised.wig diff  mean.wig input.bam 
wiggletools write  mean.normalised.posOnly.wig  gt 0 mean.normalised.wig

 wigToBigWig -clip mean.normalised.posOnly.wig  pathToChromSize mean.normalised.posOnly.bw
```

> bedGraph error line 19560665 of mean.normalised.pos.wig: chromosome GL000219.1 has size 179198 but item ends at 179204
> bedGraph error line 19563187 of mean.normalised.pos.wig: chromosome KI270330.1 has size 1652 but item ends at 1718
>  line 25: 29659 Segmentation fault     
> 
In fact trying to create bigwig with wigToBigWig ,after wiggletools use, seems to fail.

**Comment by LucoLab** [comment]
Ok I reduced the command and get : 
By the way, the bam were aligned with bwa using same genome reference.
So how to correct that ? 

> bedGraph error line 19560665 of mean.normalised.posOnly.wig: chromosome GL000219.1 has size 179198 but item ends at 179204
> bedGraph error line 19563187 of mean.normalised.posOnly.wig: chromosome KI270330.1 has size 1652 but item ends at 1718
>  Segmentation fault  

End of GL000219.1 in wig.
> GL000219.1	178701	178705	1.00fixedStep chrom=GL000219.1 start=176320 step=1
0000
> ...
> GL000219.1	178709	178718	1.000000
> GL000219.1	178721	178776	1.000000
> GL000219.1	179201	179204	1.000000

**Comment by dzerbino** [comment]
OK, this appears to come from the BWA BAM files (I guess you could examine the reads mapped to GL000219.1 and KI270330.1).

A quick fix would be to multiply by a special `lengths.bed` file that contains the lengths of the chromosomes (sorted by chromosome name), e.g.
```
GL000219.1	0	179198
KI270330.1	0	1652
```

Then "multiply" your final result by that file, e.g.:
```
wiggletools write mean.normalised.posOnly.wig mult lengths.bed gt 0 diff mean Rep1.bam Rep2.bam : input.bam

```

**Comment by ZheFrenchKitchen** [comment]
Ok thanks but I will give a try but I don't understand the trick here ? Why multiply with the good chrom sizes is doing actually ?

**Comment by dzerbino** [comment]
Sorry, I double checked and it does not work... my thought was that this function would reduce to 0 your function outside of the chromosome length, which it does, but alas it still prints out a line with value 0 outside of the chromosome. 

*However* there is a function for this, `trim`:
```
wiggletools write mean.normalised.posOnly.wig trim lengths.bed gt 0 diff mean Rep1.bam Rep2.bam : input.bam

```

**Comment by LucoLab** [comment]
Ok  I see you trim out the region outside the chromosome sizes reference.

From what I understand and after googling : 

> I see a read stands out the end of a chromosome and is flagged as unmapped (flag 0x4). What is happening here?
> Internally BWA concatenates all reference sequences into one long sequence. A read may be mapped to the junction of two adjacent reference sequences. In this case, BWA will flag the read as unmapped, but you will see position, CIGAR and all the tags. A better solution would be to choose an alternative position or trim the alignment out of the end, but this is quite complicated in programming and is not implemented at the moment.

https://seqanswers.com/forums/showthread.php?t=24005

Thanks for your help.

**Comment by ilsley** [comment]
We have run into a similar problem using wiggleTools to convert a BAM to bigWig. It is necessary to filter out the unmapped reads before running wiggleTools. This is a good workaround, but non-obvious. Would it be possible for wiggleTools to ignore unmapped reads when generating the wiggle file?

**Comment by dzerbino** [comment]
Hello @ilsley , 

That seems feasible, but I don't know the htslib API by heart. I'll have a look this weekend. 

Cheers,

Daniel

**Comment by dzerbino** [comment]
Hello again,

Reading through the WiggleTools code and htlslib documentation, WiggleTools should (in theory that is) only be picking up mapped reads from the BAM files. 

Could you please send me a SAM or BAM file to replicate?

Thanks,

Daniel

**Comment by ilsley** [comment]
Hi Daniel,

The bam file and chromosome sizes file can be found [here](https://drive.google.com/drive/folders/1OMuP3AZ7-dbOk3wUMthpX2H8vZqjygt9?usp=sharing).

These commands:
```
wiggletools write astrocyte.wig mean scale 30 astrocyte_H3K36me3.bam
wigToBigWig astrocyte.wig GRCh38.sizes astrocyte.bw
```

give the error:
`bedGraph error line 46603978 of astrocyte.wig: chromosome KI270727.1 has size 448248 but item ends at 448283
`

The relevant entry in the bam file has the 0x4 flag bit set:
`FC305KNAAXX:2:48:69:1444        20      KI270727.1      448248  0       36M     *       0       0       CAATGGAAGGGAATGGAATGTAATGGAATGGAATGG +:::;<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<    XT:A:R  NM:i:1  X0:i:2  X1:i:163        XM:i:1  XO:i:0  XG:i:0  MD:Z:20G15
`

But it appears in the wig file:
`KI270727.1      448247  448283  30.000000`

**Comment by dzerbino** [comment]
Hello @ilsley 

Thanks for the detailed explanation. 

If this read is unmapped, why does it have coordinates? Another mystery of the BAM file format...

Anyways, I'll have a look at it sometime this week.

Cheers,

Daniel

**Comment by ilsley** [comment]
From the seq answers [link](https://seqanswers.com/forums/showthread.php?t=24005) it's because "Internally BWA concatenates all reference sequences into one long sequence. A read may be mapped to the junction of two adjacent reference sequences. In this case, BWA will flag the read as unmapped, but you will see position, CIGAR and all the tags."

So, yes, non-obvious! 

Cheers,
Garth

**Comment by dzerbino** [comment]
I learned something today, thanks!

**Comment by dzerbino** [comment]
Hello @ilsley ,

I've just pushed a change, could you please give it a whirl?

If it works, could you please do me a favour and update the docker image on Dockerhub? I do not have the credentials for that. 

Cheers,

Daniel

**Comment by ilsley** [comment]
Looks good, thank you. Docker image updated!

Cheers,
Garth

**Comment by dzerbino** [comment]
Ace, thanks!
