### ISSUE TITLE
profiles - sum of output values changes based on bin size

### ISSUE THREAD

**Issue by ChiWPak** [Ensembl/WiggleTools#24]
Hi:
I'm wondering if `wiggletools profiles` (not `profile`) uses overlapping bins (rather than non-overlapping bins). Here is some output where I use the same bed file and bigwig file but change the bin size.

    wiggletools profiles - 10 ttemp.bed test.bw
    chr1    944203  959000  37328.629147    167978.831162   74658.041263    93321.661506    93321.572868    
    74657.258294    111986.227220   199975.700155    109129.104598   45518.073297

    wiggletools profiles - 50 ttemp.bed test.bw
    chr1    944203  959000  0.000000        3732.862915     3732.862915     3732.862915     7465.725829     
    5561.203934     5789.746562     11046.226993     0.000000        0.000000        11198.745338    
    3732.862915     0.000000        0.000000        0.000000        11198.606472     7465.725829     0.000000        
    3732.862915     3732.862915     7275.273640     3923.315104     0.000000        6132.560503     
    1333.165327      7046.731012     418.994817      0.000000        11198.618290    0.000000        
    11198.627154    0.000000        0.00000014931.552115     3732.862915     3732.862915     2361.607150     
    15236.254936    4799.395176     0.000000        3732.862915     7237.183202      6056.379627     
    1637.888830     3732.862915     3732.862915     0.000000        0.000000        0.000000        1180.803575

The sum of values are 1,007,875 and 187,825.3, respectively. I expected that the sum of values would be the same or similar.

**Comment by dzerbino** [comment]
Thanks for reporting that bug, now fixed on master.
