### ISSUE TITLE
test fails for one diff

### ISSUE THREAD

**Issue by rohitner** [Ensembl/WiggleTools#25]
```bash
/WiggleTools/test$ ../bin/wiggletools do isZero diff bam.bam cram.cram
[E::cram_get_ref] Failed to populate reference for id 29
[E::cram_decode_slice] Unable to fetch reference #29 167..186835
[E::cram_next_slice] Failure to decode slice
[E::cram_get_ref] Failed to populate reference for id 42
[E::cram_decode_slice] Unable to fetch reference #42 466..29856
[E::cram_next_slice] Failure to decode slice
```
All other tests pass.

**Comment by dzerbino** [comment]
I suspect this is an issue with htslib... what version are you at?

**Comment by rohitner** [comment]
I am on the bleeding edge of the repository.

**Comment by dzerbino** [comment]
Sorry, I was not clear which version are you using for both:
- Wiggletools
- htslib

**Comment by dzerbino** [comment]
Hello again Rohit, 

I am unable to reproduce the bug, could you please confirm which versions you are working from?

Cheers,

Daniel

**Comment by rohitner** [comment]
Hi Daniel,

These are the versions I am working on.
Wiggletools - `1.2.2`
htslib - `1.7-23-g9f9631d`

**Comment by dzerbino** [comment]
Sorry, I still cannot reproduce the bug with those exact versions (nor with the current head of htslib and WiggleTools).
