### ISSUE TITLE
unexpected output - wiggletools profile

### ISSUE THREAD

**Issue by ChiWPak** [Ensembl/WiggleTools#27]
I'm confused by the output of wiggletools profile - using a single entry bed file (TSS around ActB) 

```
chr7    5528101 5533101 NM_001101.3_ACTB        .       -
```

and `wiggletools profile out.txt 250 actb.bed input.bw`, this is the result (showing values near the peak)

```
115     109.794479
116     131.095570
117     144.408720
118     155.737980
119     164.613380
120     180.223719
121     189.255841
122     193.275845
123     194.267832
124     181.737781
125     165.605360
126     158.609439
127     150.256069
128     146.183820
129     132.087501
130     118.200050
131     102.276440
132     88.806671
133     82.698241
134     79.043671
135     82.907081
```
However, looking at the same bigwig file in IGV, the maximum value near the peak of ActB is <10.

![actb](https://user-images.githubusercontent.com/17429954/40443412-d5eb1aa0-5e8b-11e8-9b17-cc1470c39c16.jpg)

I'd expect the maximum value of `wiggletools profile` output to be around 10 as well.

**Comment by dzerbino** [comment]
This is because a 5000bp region is compressed into 250 bins, thus each bin represents 20bp. To conserve the overall sum of columns, each bin sums up the value at each bp it represents.

**Comment by ChiWPak** [comment]
Of course - so obvious in hindsight. Thanks!
