### ISSUE TITLE
ld: error: undefined symbol: rollYourOwn

### ISSUE THREAD

**Issue by yurivict** [Ensembl/WiggleTools#41]
```
cc -O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -L../lib -L../../libBigWig -L../../htslib wiggletools.c  -o ../bin/wiggletools 
ld: error: undefined symbol: rollYourOwn
>>> referenced by wiggletools.c
>>>               /tmp/wiggletools-47fd81.o:(main)
```

There is no ```../../libBigWig```. libbigwig is installed in $(PREFIX), you need to add ```-L$(PREFIX)/lib -lBigWig```

**Comment by joshuak94** [comment]
When are you getting this error? Are you making the tool from source (i.e. using the make command), or are you using brew to install Wiggletools?

**Comment by dzerbino** [comment]
This issue has been up for more than a year, now closing.
