### ISSUE TITLE
Unexpected behaviour with trim vs overlaps?

### ISSUE THREAD

**Issue by joshuak94** [Ensembl/WiggleTools#42]
Either I'm misunderstanding the functionality of trim and overlaps, or the behaviour isn't quite what it should be?

Specifically, running something like:
`wiggletools overlaps test/fixedStep.bw test/overlapping_coverage.wig` and running `wiggletools trim test/fixedStep.bw test/overlapping_coverage.wig` return different outputs... Since fixedStep.bw has values from position 1 through 9, and overlapping_coverage.wig has values from position 3 through 8, shouldn't all of overlapping_coverage.wig be returned by both calls?

**Comment by dzerbino** [comment]
Thanks, had not noticed.
