### ISSUE TITLE
Make errors

### ISSUE THREAD

**Issue by hinz1** [Ensembl/WiggleTools#46]
Trying to build on Ubuntu Xenial: 

mkdir -p ../bin
cc -g -Wall -O3 -std=gnu99 -L../lib -L../../libBigWig -L../../htslib wiggletools.c -lwiggletools -l:libBigWig.a -lcurl -l:libhts.a -lgsl  -lgslcblas -lz -lpthread -lm -llzma -lbz2 -o ../bin/wiggletools 
//usr/local/lib/libhts.a(hfile_s3.o): In Funktion `s3_sha256':
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:111: Nicht definierter Verweis auf `SHA256'
//usr/local/lib/libhts.a(hfile_s3.o): In Funktion `s3_sign_sha256':
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `EVP_sha256'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `HMAC'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `EVP_sha256'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `HMAC'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `EVP_sha256'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `HMAC'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `EVP_sha256'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `HMAC'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `EVP_sha256'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:116: Nicht definierter Verweis auf `HMAC'
//usr/local/lib/libhts.a(hfile_s3.o): In Funktion `s3_sign':
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:104: Nicht definierter Verweis auf `EVP_sha1'
/home/mkiefer/software/builds/augustus-3.3.3/htslib/hfile_s3.c:104: Nicht definierter Verweis auf `HMAC'
collect2: error: ld returned 1 exit status
Makefile:14: die Regel für Ziel „../bin/wiggletools“ scheiterte
make[1]: *** [../bin/wiggletools] Fehler 1
make[1]: Verzeichnis „/home/mkiefer/software/builds/WiggleTools/src“ wird verlassen
Makefile:7: die Regel für Ziel „Wiggletools“ scheiterte
make: *** [Wiggletools] Fehler 2

Any ideas what I have to change / install? 

Best,
Markus

**Comment by dzerbino** [comment]
Hello @hinz1 ,

Evidently there is an issue with your htslib installation. Do the htslib executables (e.g. tabix) work for you?

Cheers,

Daniel

**Comment by hinz1** [comment]
In fact yes, tabix works. It's the version from the Xenial repo: 1.9-393-g634aad4

**Comment by dzerbino** [comment]
Hello @hinz1 , 

apologies, I missed your response a few months back.

Did you manage to solve the problem? It seems to be deep into the compilation or linking of htslib. If htslib compiled well, then maybe the library file was not found at `../../htslib`?

HTH,

Daniel

**Comment by dzerbino** [comment]
No update in a year, closing issue.
