### ISSUE TITLE
error accesing remote bigWig

### ISSUE THREAD

**Issue by diekhans** [Ensembl/WiggleTools#49]
I am attempting to access a ENCODE bigWig by URL

`wiggletools overlaps promoter-region.bb https://encode-public.s3.amazonaws.com/2017/10/03/ad2c0f17-0824-4647-a749-74276daca7da/ENCFF278CUB.bigWig`

I get the error:

`[urlOpen] curl_easy_perform received an error: Failed writing received data to disk/application
File https://encode-public.s3.amazonaws.com/2017/10/03/ad2c0f17-0824-4647-a749-74276daca7da/ENCFF278CUB.bigWig is not in BigWig format`

If the bigWig is download locally, this works fine.

The bigBed containes one record:
`chr19	6925784	6926845`

thanks!

**Comment by dzerbino** [comment]
Hello @diekhans,

I suspect this has to do with the LibBigWig library that we use in WiggleTools.

I'll create a reproducible test then send it their way.

Cheers,

Daniel

**Comment by dzerbino** [comment]
Now discussed here: https://github.com/dpryan79/libBigWig/issues/49

**Comment by dzerbino** [comment]
Hello @diekhans ,

Thanks to Devon's advice I now got it working on remote files. Naturally, this is much slower than on a local file, no miracle there.

HTH,

Daniel

**Comment by diekhans** [comment]
So if I do an overlaps, does it still pull the whole wig?  The runtime
make is appear like it does:

  wiggletools overlaps ../promoter-region.bb https://encode-public.s3.amazonaws.com/2016/11/15/ab269604-0eeb-4fad-8754-c3cf4674fe91/ENCFF516HJR.bigWig

I can continue to do what I did to workaround the remote access error

  bigWigToBedGraph -chrom=chr19 -start=6925784 -end=6926845 $url $bg
  bedGraphToBigWig $bg /hive/data/genomes/hg38/chrom.sizes $bw

although random access in wiggletools would be useful.

**Comment by dzerbino** [comment]
Yes, it does pull the whole wig.

What exactly is you use case? Why do you want to use WiggleTools rather than bigWigToBedGraph?
- If you want to do some fancy analysis downstream for a single region you could use the `wiggletools seek` function.
- If you want to compute a statistic at multiple regions, you could use `apply`
- If you convince me of a good alternate use case, then I could quite quickly implement a `seek_regions` function, a bit like the existing `apply` functions.

**Comment by diekhans** [comment]
I want to compute AUC on a 1kb region of a crazy transcript over
lots of dataasets.

I didn't see the "seek" operator because it isn't in the help message ;-)

this seems to be exactly what I want !

**Comment by dzerbino** [comment]
Ahhh you should have said so:
`wiggletools apply AUC regions.bed signal.wig`

This does random access and allows you to check multiple regions.

`apply_paste` may also be of interest.
