### ISSUE TITLE
GSL not found using OSX binary build

### ISSUE THREAD

**Issue by maximilianh** [Ensembl/WiggleTools#5]
Many thanks for providing a OSX binary!

However, on a clean OSX install, the binary does not work:
dyld: Library not loaded: /usr/local/lib/libgsl.0.dylib
OSX does not ship with a GSL library.

I fixed it by installing the homebrew package manager and doing a "brew install gsl".
You could fix it by installing a static version of the gsl library and compiling your binary statically on OSX.

**Comment by dzerbino** [comment]
Yes, I had some trouble to get the MacOS gcc to load libraries statically, GSL in particular. I looked around, but found no serious solution (suggestions welcome).

In conclusion, until further notice, the MacOS binary requires a GSL brew install.  Thanks for letting me know that it does work in the end.

**Comment by dzerbino** [comment]
From now on, the recommended installation procedure will be through brew, making the binaries obsolete.
