### ISSUE TITLE
how to average bw files?

### ISSUE THREAD

**Issue by olechnwin** [Ensembl/WiggleTools#53]
Hi,

I tried to run the following command to average bw files and output a bw file. But the resulting bw file is not a binary file. How do I generate an averaged bw?

`wiggletools write test_comb_wiggletool.bw mean test_rep*_spike.bw`

**Comment by jma1991** [comment]
WiggleTools writes the output in uncompressed wiggle format. See this related issue for a solution: https://github.com/Ensembl/WiggleTools/issues/17#issue-226882813

**Comment by olechnwin** [comment]
Ah...I see. Thanks for your response.
