### ISSUE TITLE
greater than or equal

### ISSUE THREAD

**Issue by gevro** [Ensembl/WiggleTools#54]
Is it possible to add a gte (greater than or equal) and less than or equal?

**Comment by dzerbino** [comment]
Hello @gevro ,

Sure, it's possible, but could you describe a scenario where this change is needed? 

Cheers,

Daniel

**Comment by gevro** [comment]
Some wiggle files may have discrete values such as a mappability track for instance: values of 0.5, 0.25, 0.125, etc.
And one may want to keep all regions >=0.5. 

Of course, I could do gt 0.4999, but not as clean of a result.

Anyway, it's not crucial, but just an idea.

**Comment by gevro** [comment]
Another place this would be useful is to get two disjoint sets of regions for the genome: One with regions greater than or equal, and one with regions less than. That way the two sets together include all the regions. If there is only gt and lt, there might be a small number of regions left out, without slightly modifying the thresholds for gt and lt, which can start to get confusing.

**Comment by dzerbino** [comment]
Hello @gevro ,

Thanks for the suggestion, now implemented.

Cheers,

Daniel
