### ISSUE TITLE
gte not working and compression

### ISSUE THREAD

**Issue by gevro** [Ensembl/WiggleTools#61]
Hi,
I tested 'gte' and it isn't working. Example below. I'm guessing lte might have the same issue.

Note also that gt/gte/lt/lte are still causing compression with write_bg. I think that is useful in some cases, but not desirable in other cases. So I think it would be good to have it as an option: either with or without compression. Maybe:
  - write_bg is compressed, and
  - write_bgu is uncompressed

```
wiggletools write_bg - bin 20 scale 0.05 fillIn genome.bed blah.bw | head
chr1	0	20	0.005435
chr1	20	40	0.000000
chr1	40	60	0.000000
chr1	60	80	0.000000
chr1	80	100	0.000000
chr1	100	120	0.000000
chr1	120	140	0.000000
chr1	140	160	0.005435
chr1	160	180	0.000000
chr1	180	200	0.000000
```

```
$ wiggletools write_bg - gte 0.005435 bin 20 scale 0.05 fillIn genome.bed blah.bw | head
chr1	280	400	1.000000
chr1	420	1940	1.000000
chr1	1960	2020	1.000000
chr1	2040	2280	1.000000
chr1	2300	2400	1.000000
chr1	2420	2440	1.000000
chr1	2460	2480	1.000000
chr1	2500	2540	1.000000
chr1	2560	2600	1.000000
chr1	2640	2660	1.000000
```

```
$ wiggletools write_bg - gte 0.005434 bin 20 scale 0.05 fillIn genome.bed blah.bw | head
chr1	0	20	1.000000
chr1	140	160	1.000000
chr1	260	2280	1.000000
chr1	2300	2440	1.000000
chr1	2460	2540	1.000000
chr1	2560	2620	1.000000
chr1	2640	2880	1.000000
chr1	2900	2920	1.000000
chr1	2960	3000	1.000000
chr1	3040	3060	1.000000
```

**Comment by dzerbino** [comment]
Hello @gevro ,

Without the raw files, I was not able to reproduce your bug, however it is possible that the values at chr1:0-20 and chr1:140-160 was just below the cutoff (0.005435) and rounded up to 0.005435 when printing. 

Also, I don't understand what you mean by compression. The `gte` operator is returning all the regions that have a score greater or equal to 0.005435 as advertised. If you also want the regions with 0, I would recommend re-ordering the command as such:

`wiggletools write_bg - bin 20 fillIn genome.bed gte 0.005435 bin 20 scale 0.05 blah.bw`

HTH,

Daniel

**Comment by gevro** [comment]
Hi @dzerbino, Thanks. Here is what I mean by the gte bug and by compression:
1) gte:

In this example, there is a bin "chr1	0	20	0.005435" that should match the "gte 0.005435" filter:
```
wiggletools write_bg - bin 20 scale 0.05 fillIn genome.bed blah.bw | head
chr1	0	20	0.005435
chr1	20	40	0.000000
chr1	40	60	0.000000
chr1	60	80	0.000000
chr1	80	100	0.000000
chr1	100	120	0.000000
chr1	120	140	0.000000
chr1	140	160	0.005435
chr1	160	180	0.000000
chr1	180	200	0.000000
```

However, when adding that filter, that bin is missing:
```
$ wiggletools write_bg - gte 0.005435 bin 20 scale 0.05 fillIn genome.bed blah.bw | head
chr1	280	400	1.000000
chr1	420	1940	1.000000
chr1	1960	2020	1.000000
chr1	2040	2280	1.000000
```

Because the gte filter is applied after "bin 20 scale 0.05", it should be a simple filter that keeps any bin with that value or larger. There technically shouldn't be any issues of rounding, because the filter is applied after the bin 20 scale 0.05 calculations.


2. Compressed vs uncompressed: In the below example, there is a bin "chr1 260 2280  1.0000". However, it would be very useful to have uncompressed output after gt/gte/lt/lte, where every bin that passes the filter is listed. For example:
chr1 260 280 1.000
chr1 280 300 1.000
chr1 300 320 1.000
etc.

```
$ wiggletools write_bg - gte 0.005434 bin 20 scale 0.05 fillIn genome.bed blah.bw | head
chr1	0	20	1.000000
chr1	140	160	1.000000
chr1	260	2280	1.000000
chr1	2300	2440	1.000000
chr1	2460	2540	1.000000
````

**Comment by dzerbino** [comment]
Hello @gevro ,

1. The values are rounded just before they are printed into output (with 6 digits past the decimal dot). Therefore it is possible that a block has a value of 0.0054348, which is below 0.005435, but is rounded up to 0.005435 when printed out. 

2. I'm not getting the same results as you... 
```
noah-login-02.ebi.ac.uk>  wiggletools write_bg - gte 0.005435 bin 20 scale 0.05 fillIn genome.bed blah.bw | head
chr1	109340	110360	1.000000
```

I think this is related to Issue #62 

Cheers,

Daniel

**Comment by gevro** [comment]
Hi Daniel,
Regarding point #2, that is actually a different blah.bw file than the one I sent you, which is why you're getting a different result. However, the point I'm trying to make is that write_bg is still compressing neighboring bins that have the same value. However, it would be very useful to have an option for 'write_bgu' that does not do this. Is this possible to do?
Thanks!

**Comment by dzerbino** [comment]
Hello @gevro ,

Actually, you are right, there was an implicit compression system which I had forgotten about, and which I now cleared up.

Could you please try again on master?

Cheers,

Daniel

**Comment by gevro** [comment]
Thanks. Is it possible to add write_bg with an option for either compressed or uncompressed? Maybe with a flag? Or write_bgu versus write_bgc ?

There are use cases for both options, so it would be very useful to have both.

**Comment by dzerbino** [comment]
I have just now implemented a new "compress" keyword on master (cf README).

Let me know,

Daniel

**Comment by gevro** [comment]
Thanks, works.
