### ISSUE TITLE
wiggletools seek combines regions with multiple zero points (undesiderable)

### ISSUE THREAD

**Issue by SimonaSecomandi** [Ensembl/WiggleTools#68]
Hi,

I'm trying to extract a region from a wiggle file like so:

`wiggletools write output.wig seek SUPER_6 53887433 53926022 file.wig `

The wig file has base-by-base values and this command tends to combine regions with multiple zero values like so:

....
0.446000
0.447000
-0.574000
0.447000
0.447000
0.429000
SUPER_6 53889550        53889558        0.000000
fixedStep chrom=SUPER_6 start=53889559 step=1
-0.323000
-0.574000
-1.049000
0.524000
-0.231000
0.447000
0.447000
...

This is undesideble and the conversion of the wig file in bed format fails due to that lines (e.g. SUPER_6 53889550 53889558       0.000000).

Can this merging be avoided? Many thanks.

**Comment by dzerbino** [comment]
Dear @SimonaSecomandi ,

I think what you want is the `write_bg` command that writes straight to bedGraph, as in: 

```
wiggletools write_bg output.wig seek SUPER_6 53887433 53926022 file.wig
```

Hope this helps,

Daniel

**Comment by SimonaSecomandi** [comment]
That worked fine to obtain the bed file!! 

I was also wondering if there are ways to obtain a correct wig file with wiggletools seek for visualization.

Many thanks
