### ISSUE TITLE
Using wiggletools overlaps processed data, but the results cannot open by IGV

### ISSUE THREAD

**Issue by lexie-lee** [Ensembl/WiggleTools#70]
Hello,

I used the overlaps function to combine my two bw data.  The command are 

`wiggletools overlaps /Volumes/PBLAB/Seq_data_temp/F03_PBS_A1/F03_PBS_A1.bw /Volumes/PBLAB/Seq_data_temp/F03_PBS_A2/F03_PBS_A2.bw > /Volumes/PBLAB/Seq_data_temp/F03_PBS_A1.bw`

The original two data both can open by IGV, but the combined bw file can not....

Do you know why this happens? How can I do to solve this?

**Comment by dzerbino** [comment]
Dear @lexie-lee 

WiggleTools outputs in wiggle format (i.e. text based) as opposed to BigWig (which is compressed and indexed). 

You therefore need to convert it to BW, using [wigToBigWig](https://www.encodeproject.org/software/wigtobigwig/).

Hope this helps,

Daniel

**Comment by lexie-lee** [comment]
Thanks a lot !!! 
I will try your suggestion later, and I just find a way to merge bw files in IGV.

Thanks again!
