### ISSUE TITLE
bigBed file ending not recognised

### ISSUE THREAD

**Issue by stevenwgen** [Ensembl/WiggleTools#71]
Could wiggletools be modified slightly to allow the file ending bigBed to be recognised as well as bb for bigBed files? This is the file ending used be the ENCODE projects and others. Thanks

**Comment by dzerbino** [comment]
Hello @stevenwgen ,

Hope you are doing well!

Your request is pretty straightforward, I can do it this weekend.

All the best,

Daniel

**Comment by dzerbino** [comment]
Hello again,

Here is the change, hope it helps!

Note that it is currently only on master, not on Brew, Conda nor DockerHub, as these only get updated periodically. 

Nonetheless, if you are using brew, you can use `brew install --HEAD wiggletools`.

Cheers,

Daniel
