### ISSUE TITLE
Error installing 1.2.10

### ISSUE THREAD

**Issue by gevro** [Ensembl/WiggleTools#73]
Hi,
I'm trying to install v1.2.10 with conda for consistency with a prior pipeline, but getting this error within a brand new conda environment I created just for wiggletools.

root@009140d52add:~# conda install -c bioconda wiggletools=1.2.10
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                           

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.33=0
  - wiggletools=1.2.10 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.33

**Comment by dzerbino** [comment]
Dear @gevro , 

I'm afraid we do not maintain the Conda installation recipe for WiggleTools. 

Looking at it, this would require deeper knowledge of Conda.  In particular, the [recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/wiggletools/meta.yaml) itself does not appear to specify versions. Also, I do not understand why ==2.33 is incompatible with >=2.17.

Could you please refer this to the bioconda team?

Cheers,

Daniel

**Comment by gevro** [comment]
Thanks. I fixed it by updating the base conda version.
