### ISSUE TITLE
Cannot find libhts.so.1

### ISSUE THREAD

**Issue by CLAIRE-cuhk** [Ensembl/WiggleTools#79]
Hi,
I am trying to install WiggleTools with command conda install -c bioconda wiggletools. Here is the message I got after installation: 
$wiggletools --help
wiggletools: error while loading shared libraries: libhts.so.1: cannot open shared object file: No such file or directory

When I do which wiggletools, it appears the tool is already in the environment. 
$which wiggletools
~/Scratch/bioinfo_tools/miniconda/install/envs/bioinfo/bin/wiggletools

Could you help that out? 

Thank you very much.

**Comment by dzerbino** [comment]
Dear @CLAIRE-cuhk ,

Thank you for your interest in Wiggletools. We do not maintain the conda installer, so it is hard to comment on why the dependency is broken, but in short you are missing `htslib`. 

It would seem from the [conda help pages](https://anaconda.org/bioconda/htslib) that you can install it with the following command: 

```
conda install -c bioconda htslib
```

Hope this helps,

Daniel

**Comment by sgiorgetti** [comment]
Closing because of ageing. Please @CLAIRE-cuhk or anyone, feel free to re-open it should you need it.
