### ISSUE TITLE
README: Instructions miss to initialize HTSlib submodules

### ISSUE THREAD

**Issue by paulmenzel** [Ensembl/WiggleTools#80]
https://github.com/Ensembl/WiggleTools/blob/b082056006db4738dcfd42c8fb76be47748b419d/README.md?plain=1#L56-L62

The above instructions miss to initialize the submodules as documented by HTSlib:

https://github.com/samtools/htslib/blob/f307dfbf5c7723956e788e0bdab269fe3d626b83/INSTALL#L66-L72

**Comment by dzerbino** [comment]
Hello both,

Thanks for the report and the fix, the PR was just merged. 

Regards,

Daniel

**Comment by paulmenzel** [comment]
@sgiorgetti, thank you for documenting the instructions also in this issue.

@all, thank you for the quick improvement done by merge/pull request https://github.com/Ensembl/WiggleTools/pull/81.

PS: If you add the tag

> Resolves: https://github.com/Ensembl/WiggleTools/issues/80

GitHub is going to link the issue and merge/pull request and automatically close the issue, once the merge/pull request is submitted.
