### ISSUE TITLE
binary not working on mac OSX Yosemite version 10.10.1

### ISSUE THREAD

**Issue by crazyhottommy** [Ensembl/WiggleTools#9]
not sure why:

```
➜  software ./wiggletools_x86_64_linux 
zsh: exec format error: ./wiggletools_x86_64_linux
➜  software brew install gsl
Warning: gsl-1.16 already installed
➜  software uname -m
x86_64

```

Thanks very much.

**Comment by dzerbino** [comment]
That would be because the binary is for Linux. I forgot to add a MacOS one.

**Comment by crazyhottommy** [comment]
could you please add that? thanks!

**Comment by dzerbino** [comment]
Might take a while unfortunately, my upgrade to El Capitan messed up quite a few things apparently.

**Comment by dzerbino** [comment]
OK, I gave it a try, let me know if it works on your system.

If it does not work at first, try installing XCode.

**Comment by crazyhottommy** [comment]
jt seems to work! Thanks.

Ming
