### ISSUE TITLE
The compiler raised syntax errors when compiling the "bigWiggleReader.c" source

### ISSUE THREAD

**Issue by sklarame** [Ensembl/WiggleTools#90]
Thanks for developing this package! Recently I tried to install the package following the "Build from source" instruction in [README.md]. Things all went well until the compiler raised such syntax errors when I executed "make" command in the WiggleTools directory:

bigWiggleReader.c: In function ‘readBigWiggleRegion’:
bigWiggleReader.c:55:12: error: expected ‘;’ before ‘if’
   55 |   start = 1
      |            ^
      |            ;
   56 |  if (stop < 1)
      |  ~~
bigWiggleReader.c:59:7: error: ‘iter’ undeclared (first use in this function)
   59 |  if (!iter)
      |       ^~~~

After checking and completing missing semicolons ';' around such lines, and revising the line 59 as "if (iter==NULL)", the source was compiled, and the "make" process can be completed. The resulting binary did work so far.
Hope this information might help.
Best wishes!

**Comment by dzerbino** [comment]
Now fixed, thanks for reporting that issue!
